aws:
    s3BucketName: <bucket-name> #(required)
    profileName: <aws-cli profile name> #(required)
    region: <aws-region-name> (e.g. us-west-2) #(required)
    
backup:
    # valid choices for storage class are: STANDARD | REDUCED_REDUNDANCY | STANDARD_IA | ONEZONE_IA | INTELLIGENT_TIERING | GLACIER | DEEP_ARCHIVE | GLACIER_IR
    defaultS3StorageClass: <stroge-class> #(required)    
    # this prefix will be prepended to all desiniation prefixes, use your computer hostname if backing up from multiple sources
    defaultPrefixToPrepend: <default-prefix> #(optional, leave blank if not needed)
    folders:
        - 
            srcPath: C:\Temp\Misc1
            destPrefix: Temp/Misc1
            gzip: false
            # empty means use global default
            s3StorageClass: 
        - 
            srcPath: C:\Temp\Misc2
            destPrefix: Temp/Misc2
            gzip: true
            s3StorageClass: GLACIER_IR
    
    # Pattern for matching directories or files to exclude
    # * 	matches any sequence of non-path-separators
    # ** 	matches any sequence of characters, including path separators
    # ? 	matches any single non-path-separator character
    # [class] 	matches any single non-path-separator character against a class of characters (see below)
    # {alt1,...} 	matches a sequence of characters if one of the comma-separated alternatives matches
    globalExcludes:
        - '**/node_modules/**'
        - '**/bin/**'
        - '**/.git/**'
        - '**/.vs/**'
        - '**/packages/**'
        - '**/obj/**'
        - '**/debug/**'
        - '**/bzr/**'
        - '**/svn/**'
        - '**/build/**'
        - '**/boto/**'
        - '**/botocore/**'